### ISSUE TITLE
Fehlermeldung am Ende des Publish-Vorgangs, wenn Klassifikationen ausgeblendet sind

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/application#1018]
Unter PHP 7 kommt am Ende des Publish-Vorgangs die Fehlermeldung

![grafik](https://user-images.githubusercontent.com/49676210/228501598-c9683b19-dfa2-47ac-82ba-d940e3a265fc.png)

In opus.log findet sich dazu

> 2023-03-29T12:01:17+02:00 ERR (ID 64240c6ced861): Document could not be stored successfully: RoleId must be set when storing Collection! Model: Opus\Document Field: Collection.
> Thrown in /opt/opus/test8/opus4/vendor/opus4-repo/framework/library/Opus/Collection.php:890
> 2023-03-29T12:01:17+02:00 ERR (ID 64240c6ced861): Request '/test8/publish/deposit/deposit'
> 2023-03-29T12:01:17+02:00 ERR (ID 64240c6ced861): ErrorController: error type = EXCEPTION_OTHER
> 2023-03-29T12:01:17+02:00 ERR (ID 64240c6ced861): ErrorController: exception = Application_Exception: publish_error_unexpected in /opt/opus/test8/opus4/modules/publish/controllers/DepositController.php:141
> Stack trace:
> #0 /opt/opus/test8/opus4/vendor/opus4/zf1-future/library/Zend/Controller/Action.php(516): Publish_DepositController->depositAction()
> #1 /opt/opus/test8/opus4/vendor/opus4/zf1-future/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('depositAction')
> #2 /opt/opus/test8/opus4/vendor/opus4/zf1-future/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
> #3 /opt/opus/test8/opus4/vendor/opus4/zf1-future/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
> #4 /opt/opus/test8/opus4/vendor/opus4/zf1-future/library/Zend/Application.php(400): Zend_Application_Bootstrap_Bootstrap->run()
> #5 /opt/opus/test8/opus4/public/index.php(86): Zend_Application->run()
> #6 {main}

In der Datenbank bleiben rudimentäre "temporary"-Datensätze erhalten.

Unter PHP 8 tritt der Fehler nicht auf.

_Originally posted by @alw-bsz in https://github.com/OPUS4/community/discussions/6#discussioncomment-5464096_

**Comment by j3nsch** [comment]
Das Problem ist neu. Mit der Demo-Instanz, OPUS 4.7.1.2, tritt es nicht auf, wenn Klassifikationen ausgeblendet sind. Vermutlich ist es letztendlich wieder eine Vergleichsoperation, die jetzt strikt ist und nun schief läuft.

**Comment by j3nsch** [comment]
Die Ursache war durch Debugging schwer zu finden, weil am Anfang unklar ist wo man ansetzen muss. Der Code ist unübersichtlich. Am Ende hat ein Vergleich des geänderten Publish-Modules mit dem aktuellen Release zum Ziel geführt. Das Problem sollte gefixt sein.
