### ISSUE TITLE
Abbruch des DOI-Imports im Publishformular bei hoher Anzahl von Autoren

### ISSUE THREAD

**Issue by stconradr** [OPUS4/application#1218]
Beim Übertragen der Daten über den DOI-Import im Publishformular kommt es zu einem Abbruch, wenn die Anzahl der Autoren hoch ist. Testdatensatz beinhaltet 270 Autoren.

Beispiel-DOI: 10.1038/s41562-022-01319-5

Folgende Fehlermeldung erscheint:

**Anwendungsfehler**
Es wurde leider kein Button erkannt. Eventuell wurde nach dem Hinzufügen oder Löschen eines Feldes ein Reload der Formular-Seite ausgeführt. Bitte beginnen den Veröffentlichungsprozess erneut. 

**Stacktrace**

  Application_Exception: publish_no_pressed_button_found in /home/opus/opus4-UBICO/modules/publish/controllers/FormController.php:289
Stack trace:
#0 /home/opus/opus4-UBICO/vendor/opus4/zf1-future/library/Zend/Controller/Action.php(516): Publish_FormController->checkAction()
#1 /home/opus/opus4-UBICO/vendor/opus4/zf1-future/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('checkAction')
#2 /home/opus/opus4-UBICO/vendor/opus4/zf1-future/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /home/opus/opus4-UBICO/vendor/opus4/zf1-future/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#4 /home/opus/opus4-UBICO/vendor/opus4/zf1-future/library/Zend/Application.php(400): Zend_Application_Bootstrap_Bootstrap->run()
#5 /home/opus/opus4-UBICO/public/index.php(86): Zend_Application->run()
#6 {main}

**Request**

        Zend_Controller_Request_Http::__set_state(array(
   '_paramSources' => 
  array (
    0 => '_GET',
    1 => '_POST',
  ),
   '_requestUri' => '/opus4-UBICO/publish/form/check',
   '_baseUrl' => '/opus4-UBICO',
   '_basePath' => NULL,
   '_pathInfo' => '/publish/form/check',
   '_params' => 
  array (
    'module' => 'publish',
    'controller' => 'form',
    'action' => 'check',
  ),
   '_rawBody' => NULL,
   '_aliases' => 
  array (
  ),
   '_dispatched' => true,
   '_module' => 'publish',
   '_moduleKey' => 'module',
   '_controller' => 'form',
   '_controllerKey' => 'controller',
   '_action' => 'check',
   '_actionKey' => 'action',
))

**Comment by j3nsch** [comment]
Es sieht nicht so aus, als ob eine harte Grenze für die Anzahl der Autoren im Publish-Formular festgelegt wurde. Irgend etwas wird vermutlich einfach zu groß. Oder vielleicht greift auch ein Schutzmechanismus vom Server, weil ja anscheinend für jeden zusätzlichen Autoren, das Formular neu aufgebaut wird (viele schnelle HTTP-Requests). Auf jeden Fall ist die Art und Weise, wie das im Publish-Modul funktioniert (unnötig) kompliziert und sehr unübersichtlich. Das Formular muss neu implementiert werden und der CrossRef-Import sollte generell nicht auf dem Formular aufsetzen. Der Import muss auch neu implementiert werden, wenn das Formular ersetzt wird.

Das kein Button erkannt wurde deutet darauf hin, dass der Request zu groß geworden ist und nicht mehr vollständig auf dem Server ankommt. Die Grenze für POST-Requests sollte allerdings für OPUS 4 recht groß sein, weil wir ja auch Dateien hochladen können.

**Comment by stconradr** [comment]
Gibt es möglicherweise eine Begrenzung im Publishformular?
Ein ähnliches Problem beim  Metadatenformular mit der Anzahl von Autoren ist im Issue https://github.com/OPUS4/application/issues/447 beschrieben.

**Comment by j3nsch** [comment]
Der Defaultwert für `post_max_size` ist wohl 8 MB. Ich kann mir vorstellen, dass das überschritten wird, bei mehreren hundert Autoren. Diese Einstellung ist unabhängig von dem Wert für die maximale Dateigröße.

**Comment by stconradr** [comment]
Der Wert in der Apache-Umgebung beträgt post_max_size = 270M. Eine Erhöhung auf 500 MB war nicht erfolgreich.
Der Defaultwert post_max_size = 8MB ist nur in der CLI-Umgebung eingestellt.

@alw-bsz, könnt ihr den Fehler auf eurem Server reproduzieren? (Test-DOI 10.1038/s41562-022-01319-5)

**Comment by alw-bsz** [comment]
Bei uns auf dem Testserver kann der Datensatz ohne Fehler importiert werden. Es könnte tatsächlich an post_max_size liegen. Der Parameter ist bei uns auf 3000M gesetzt.

**Comment by stconradr** [comment]
@alw-bsz, ok, gut dass es bei euch geht. Die Erhöhung des Parameters hat auch nichts gebracht.
Möglicherweise ist es noch ein anderer Parameter bei PHP.

**Comment by j3nsch** [comment]
Das folgende ist vielleicht auch ein Faktor.

https://www.php.net/manual/en/info.configuration.php#ini.max-input-vars

**Comment by stconradr** [comment]
Der Parameter "max_input_vars" in der php.ini war ausschlaggebend, dass es jetzt funktioniert. Dieser Parameter muss gesetzt sein.

; How many GET/POST/COOKIE input variables may be accepted
	  
max_input_vars = 1500

Danke für die Unterstützung an @j3nsch und @alw-bsz.

**Comment by j3nsch** [comment]
Das sollte in die Dokumentation aufgenommen werden.
