### ISSUE TITLE
DB-Exception beim Versuch einen neuen Account ohne Passwort zu speichern

### ISSUE THREAD

**Issue by saschaszott** [OPUS4/application#375]
Ich habe im Formular zum Anlegen eines neuen Accounts im entsprechenden Feld kein Passwort gesetzt. Hierbei handelt es sich um ein Pflichtfeld.

Nach dem Submit des Formulars gibt es eine `Opus\Security\SecurityException`.

Relevante Auszüge aus dem Logfile:

```
2020-12-07T17:33:33+01:00 ERR (ID 5fce595aaec4a): Opus\Account::store: Unknown exception while storing account: SQLSTATE[HY000]: General error: 1364 Field 'password' doesn't have a default value, query was: INSERT INTO `accounts` (`login`) VALUES (?)


2020-12-07T17:33:33+01:00 ERR (ID 5fce595aaec4a): ErrorController: exception = Opus\Security\SecurityException: Caught exception.  Please consult the server logfile. in /var/local/opus4/vendor/opus4-repo/framework/library/Opus/Account.php:202
Stack trace:
#0 /var/local/opus4/library/Application/Controller/ActionCRUD.php(319): Opus\Account->store()
#1 /var/local/opus4/library/Application/Controller/ActionCRUD.php(218): Application_Controller_ActionCRUD->handleModelPost()
…
```

Der HTTP POST-Request auf `/admin/account/new`, der den Fehler provoziert, hat folgende Payload:

```
username: doe
firstname: 
lastname: 
email: 
password: 
confirmPassword: 
roles[accesstest]: 0
roles[administrator]: 0
roles[collectionsadmin]: 0
roles[docsadmin]: 0
roles[fulladmin]: 0
roles[guest]: 0
roles[helppagecontrolleraccess]: 0
roles[indexmaintenanceaccess]: 0
roles[jobaccess]: 0
roles[licenceadmin]: 0
roles[reviewer]: 0
roles[securityadmin]: 0
roles[setupmoduleaccess]: 0
roles[staticpagecontrolleraccess]: 0
roles[sworduser]: 0
roles[testuserrole]: 0
roles[translationcontrolleraccess]: 0
Id: 
Save: Speichern
```

**Comment by j3nsch** [comment]
Unschön, aber nicht kritisch. Wird evtl. für 4.7.1 erledigt, aber die anderen Aufgaben, insbesondere der Umstieg auf Laminas sind im Augenblick wichtiger.

**Comment by saschaszott** [comment]
Ich werde es gleich mit einem PR beheben - keine große Sache. Mir war es gerade nur zufällig aufgefallen, als ich mir nochmal abschließend das Passworthandling angesehen habe.

**Comment by j3nsch** [comment]
Validierung für neue Accounts ist jetzt gefixt.
